--[[ The Catalogue -- vanilla ids that are not merchandise.

     GENERATED FILE. Do not edit by hand: tools/import_prices.sh rewrites it wholesale
     from tools/reference/PZ_prices_B42.20.4.md, from the rows that study marks EXCLUIR.

     These are not items anyone would call worthless -- a low price is what worthless
     means. They are not OBJECTS: debug and test fixtures, corpses, the wound and bandage
     overlays the health system paints on a body, hair and beard stubble, and the Money
     the catalogue itself pays in.

     WHY THIS FILE EXISTS AT ALL, rather than just leaving them unpriced. Nothing here is
     the last word on price -- the formula fallback is. Omit a price and the fallback
     works one out, and roundPrice floors at $1, so a debug water bucket appears on the
     shelf for a dollar. The index has to refuse them BEFORE any pricing layer is asked,
     which is what TC.EXCLUDED_ITEMS does.

     Merged into the hand-written list in TC_Config.lua rather than replacing it: that
     one holds our own parcels, which are packaging and not vanilla's business.
]]

TheCatalogue = TheCatalogue or {}
TheCatalogue.EXCLUDED_ITEMS = TheCatalogue.EXCLUDED_ITEMS or {}

local NOT_MERCHANDISE = {
    "Base.Animal",
    "Base.Animal_Item_Dummy",
    "Base.Bandage_Abdomen",
    "Base.Bandage_Abdomen_Blood",
    "Base.Bandage_Chest",
    "Base.Bandage_Chest_Blood",
    "Base.Bandage_Groin",
    "Base.Bandage_Groin_Blood",
    "Base.Bandage_Head",
    "Base.Bandage_Head_Blood",
    "Base.Bandage_LeftFoot",
    "Base.Bandage_LeftFoot_Blood",
    "Base.Bandage_LeftHand",
    "Base.Bandage_LeftHand_Blood",
    "Base.Bandage_LeftLowerArm",
    "Base.Bandage_LeftLowerArm_Blood",
    "Base.Bandage_LeftLowerLeg",
    "Base.Bandage_LeftLowerLeg_Blood",
    "Base.Bandage_LeftUpperArm",
    "Base.Bandage_LeftUpperArm_Blood",
    "Base.Bandage_LeftUpperLeg",
    "Base.Bandage_LeftUpperLeg_Blood",
    "Base.Bandage_Neck",
    "Base.Bandage_Neck_Blood",
    "Base.Bandage_RightFoot",
    "Base.Bandage_RightFoot_Blood",
    "Base.Bandage_RightHand",
    "Base.Bandage_RightHand_Blood",
    "Base.Bandage_RightLowerArm",
    "Base.Bandage_RightLowerArm_Blood",
    "Base.Bandage_RightLowerLeg",
    "Base.Bandage_RightLowerLeg_Blood",
    "Base.Bandage_RightUpperArm",
    "Base.Bandage_RightUpperArm_Blood",
    "Base.Bandage_RightUpperLeg",
    "Base.Bandage_RightUpperLeg_Blood",
    "Base.BareHands",
    "Base.Bitters",
    "Base.BucketWaterDebug",
    "Base.CorpseAnimal",
    "Base.CorpseFemale",
    "Base.CorpseMale",
    "Base.DebugFluid",
    "Base.DentedCan_Open",
    "Base.FISH_DEV_ITEM",
    "Base.F_Hair_Stubble",
    "Base.Hat_SantaHatDebug",
    "Base.M_Beard_Stubble",
    "Base.M_Hair_Stubble",
    "Base.Money",
    "Base.MoneyBundle",
    "Base.MysteryCan_Open",
    "Base.Stairs",
    "Base.TestDebugWater",
    "Base.TestHotDrink",
    "Base.TestMug",
    "Base.TestWaterMug",
    "Base.WaterDrop",
    "Base.WaterRationCan_Open",
    "Base.Wound_Abdomen_Bite_Female",
    "Base.Wound_Abdomen_Bite_Male",
    "Base.Wound_Abdomen_Laceration_Female",
    "Base.Wound_Abdomen_Laceration_Male",
    "Base.Wound_Abdomen_Scratch_Female",
    "Base.Wound_Abdomen_Scratch_Male",
    "Base.Wound_Chest_Bite_Female",
    "Base.Wound_Chest_Bite_Male",
    "Base.Wound_Chest_Laceration_Female",
    "Base.Wound_Chest_Laceration_Male",
    "Base.Wound_Chest_Scratch_Female",
    "Base.Wound_Chest_Scratch_Male",
    "Base.Wound_Groin_Bite_Female",
    "Base.Wound_Groin_Bite_Male",
    "Base.Wound_Groin_Laceration_Female",
    "Base.Wound_Groin_Laceration_Male",
    "Base.Wound_Groin_Scratch_Female",
    "Base.Wound_Groin_Scratch_Male",
    "Base.Wound_LForearm_Bite_Female",
    "Base.Wound_LForearm_Bite_Male",
    "Base.Wound_LForearm_Laceration_Female",
    "Base.Wound_LForearm_Laceration_Male",
    "Base.Wound_LForearm_Scratch_Female",
    "Base.Wound_LForearm_Scratch_Male",
    "Base.Wound_LHand_Bite_Female",
    "Base.Wound_LHand_Bite_Male",
    "Base.Wound_LHand_Laceration_Female",
    "Base.Wound_LHand_Laceration_Male",
    "Base.Wound_LHand_Scratch_Female",
    "Base.Wound_LHand_Scratch_Male",
    "Base.Wound_LUArm_Bite_Female",
    "Base.Wound_LUArm_Bite_Male",
    "Base.Wound_LUArm_Laceration_Female",
    "Base.Wound_LUArm_Laceration_Male",
    "Base.Wound_LUArm_Scratch_Female",
    "Base.Wound_LUArm_Scratch_Male",
    "Base.Wound_Neck_Bite_Female",
    "Base.Wound_Neck_Bite_Male",
    "Base.Wound_Neck_Laceration_Female",
    "Base.Wound_Neck_Laceration_Male",
    "Base.Wound_Neck_Scratch_Female",
    "Base.Wound_Neck_Scratch_Male",
    "Base.Wound_RForearm_Bite_Female",
    "Base.Wound_RForearm_Bite_Male",
    "Base.Wound_RForearm_Laceration_Female",
    "Base.Wound_RForearm_Laceration_Male",
    "Base.Wound_RForearm_Scratch_Female",
    "Base.Wound_RForearm_Scratch_Male",
    "Base.Wound_RHand_Bite_Female",
    "Base.Wound_RHand_Bite_Male",
    "Base.Wound_RHand_Laceration_Female",
    "Base.Wound_RHand_Laceration_Male",
    "Base.Wound_RHand_Scratch_Female",
    "Base.Wound_RHand_Scratch_Male",
    "Base.Wound_RUArm_Bite_Female",
    "Base.Wound_RUArm_Bite_Male",
    "Base.Wound_RUArm_Laceration_Female",
    "Base.Wound_RUArm_Laceration_Male",
    "Base.Wound_RUArm_Scratch_Female",
    "Base.Wound_RUArm_Scratch_Male",
    "Base.YardstickDEBUG",
    "Base.ZedDmg_BACK_Slash",
    "Base.ZedDmg_BACK_Spine",
    "Base.ZedDmg_BELLY_Bullet",
    "Base.ZedDmg_BELLY_Shotgun",
    "Base.ZedDmg_BELLY_Skin",
    "Base.ZedDmg_BELLY_Slash",
    "Base.ZedDmg_BellySlashLeft",
    "Base.ZedDmg_BellySlashRight",
    "Base.ZedDmg_BulletBelly01",
    "Base.ZedDmg_BulletBelly02",
    "Base.ZedDmg_BulletBelly03",
    "Base.ZedDmg_BulletChest01",
    "Base.ZedDmg_BulletChest02",
    "Base.ZedDmg_BulletChest03",
    "Base.ZedDmg_BulletChest04",
    "Base.ZedDmg_BulletFace01",
    "Base.ZedDmg_BulletFace02",
    "Base.ZedDmg_BulletForehead01",
    "Base.ZedDmg_BulletForehead02",
    "Base.ZedDmg_BulletForehead03",
    "Base.ZedDmg_BulletLeftTemple",
    "Base.ZedDmg_BulletRightTemple",
    "Base.ZedDmg_CHEST_Bullet",
    "Base.ZedDmg_CHEST_Shotgun",
    "Base.ZedDmg_CHEST_Slash",
    "Base.ZedDmg_ChestSlashLeft",
    "Base.ZedDmg_FaceSkullLeft",
    "Base.ZedDmg_FaceSkullRight",
    "Base.ZedDmg_HEAD_Bullet",
    "Base.ZedDmg_HEAD_Shotgun",
    "Base.ZedDmg_HEAD_Skin",
    "Base.ZedDmg_HEAD_Slash",
    "Base.ZedDmg_HeadSlashCentre01",
    "Base.ZedDmg_HeadSlashCentre02",
    "Base.ZedDmg_HeadSlashCentre03",
    "Base.ZedDmg_HeadSlashLeft01",
    "Base.ZedDmg_HeadSlashLeft02",
    "Base.ZedDmg_HeadSlashLeft03",
    "Base.ZedDmg_HeadSlashLeftBack01",
    "Base.ZedDmg_HeadSlashLeftBack02",
    "Base.ZedDmg_HeadSlashRight01",
    "Base.ZedDmg_HeadSlashRight02",
    "Base.ZedDmg_HeadSlashRight03",
    "Base.ZedDmg_HeadSlashRightBack01",
    "Base.ZedDmg_HeadSlashRightBack02",
    "Base.ZedDmg_Mouth01",
    "Base.ZedDmg_Mouth02",
    "Base.ZedDmg_MouthLeft",
    "Base.ZedDmg_MouthRight",
    "Base.ZedDmg_NECK_Bite",
    "Base.ZedDmg_NeckBiteBackLeft",
    "Base.ZedDmg_NeckBiteBackRight",
    "Base.ZedDmg_NeckBiteFrontLeft",
    "Base.ZedDmg_NeckBiteFrontRight",
    "Base.ZedDmg_NoChin",
    "Base.ZedDmg_NoEarLeft",
    "Base.ZedDmg_NoEarRight",
    "Base.ZedDmg_NoNose",
    "Base.ZedDmg_RibsLeft",
    "Base.ZedDmg_RibsRight",
    "Base.ZedDmg_ShotgunBelly",
    "Base.ZedDmg_ShotgunChestCentre",
    "Base.ZedDmg_ShotgunChestLeft",
    "Base.ZedDmg_ShotgunChestRight",
    "Base.ZedDmg_ShotgunFaceFull",
    "Base.ZedDmg_ShotgunFaceLeft",
    "Base.ZedDmg_ShotgunFaceRight",
    "Base.ZedDmg_ShotgunLeft",
    "Base.ZedDmg_ShotgunRight",
    "Base.ZedDmg_ShoulderSlashLeft",
    "Base.ZedDmg_ShoulderSlashRight",
    "Base.ZedDmg_SkullCap",
    "Base.ZedDmg_SkullUpLeft",
    "Base.ZedDmg_SkullUpRight",
}

for _, id in ipairs(NOT_MERCHANDISE) do
    TheCatalogue.EXCLUDED_ITEMS[id] = true
end
