#!/bin/sh
# Rebuild TC_PriceTable.lua and TC_ExcludedItems.lua from the vanilla price study.
#
#     sh tools/import_prices.sh
#
# WHY IMPORTED AND NOT COMPUTED. Prices used to be generated by tools/gen_prices.ps1 from
# the game's item scripts. That formula could read everything an item DECLARES --
# category, weight, calories, MaxDamage, Capacity -- and nothing about what an item is
# FOR, so it put a hunting rifle and a fireplace poker of the same mass in the same
# place. tools/reference/PZ_prices_B42.20.4.md prices all 5,092 vanilla ids one at a
# time, from 1993 US replacement cost and then survival utility in Knox County.
#
# TWO OUTPUTS, AND THE SECOND ONE MATTERS. 194 of those ids are not merchandise: debug
# items, corpses, wound and bandage overlays, hair stubble, Money. Omitting their price
# is not enough -- the formula fallback would price them anyway and roundPrice floors at
# $1, which is exactly how a debug bucket ends up on the shelf for a dollar. They are
# written into TC_ExcludedItems.lua, which merges them into TC.EXCLUDED_ITEMS so the
# index refuses them before any pricing layer is consulted.
#
# COLUMNS BY NAME, NOT POSITION. The study's full table is split into fourteen chunks,
# each repeating the same header. This reads that header and looks up "Item ID",
# "Status" and "Compra ($)" by name, so a future revision that adds a column in the
# middle does not silently shift the price by one field.
#
# `Compra ($)` is the integer the shop shows, already rounded the way roundPrice would.
# `Valor PZ (Cr)` is the analytic figure behind it and is deliberately NOT imported.

set -u
cd "$(dirname "$0")/.." || exit 1

SOURCE="tools/reference/PZ_prices_B42.20.4.md"
PRICES="42/media/lua/shared/TheCatalogue/TC_PriceTable.lua"
EXCLUDED="42/media/lua/shared/TheCatalogue/TC_ExcludedItems.lua"

[ -f "$SOURCE" ] || { echo "missing $SOURCE" >&2; exit 1; }

sell=$(mktemp) || exit 1
skip=$(mktemp) || exit 1
trap 'rm -f "$sell" "$skip"' EXIT

awk -F'|' -v sellFile="$sell" -v skipFile="$skip" '
    # Any row naming a column takes over as the current header. The document holds
    # several tables: summary ones with an "Item ID" and a "Status" but a price column
    # called something else, and a per-family one with prices but no status. Only a
    # header carrying all THREE names is the full table, and anything under a header
    # that is missing one is skipped entirely -- an awk field index of 0 is $0, so a
    # missing column would otherwise read the whole line as a price.
    /\|/ && /Item ID/ {
        delete col
        for (i = 2; i < NF; i++) {
            name = $i
            gsub(/^[ \t]+|[ \t]+$/, "", name)
            col[name] = i
        }
        usable = (col["Item ID"] && col["Status"] && col["Compra ($)"])
        next
    }

    !usable { next }

    {
        id = $(col["Item ID"]);   gsub(/[ `]/, "", id)
        if (id !~ /^[A-Za-z]+\.[A-Za-z0-9_]+$/) next

        status = $(col["Status"]); gsub(/[ \t]/, "", status)

        # Prices are written Brazilian style, so the dot is a thousands separator and
        # 2.700 is two thousand seven hundred. Dropping it before the integer test is
        # what stops every item over $999 -- generators, gold, ham radios -- from being
        # silently skipped and falling through to the formula.
        price = $(col["Compra ($)"]); gsub(/[ \t$.]/, "", price)

        if (status == "EXCLUIR")       { print id > skipFile; next }
        if (status != "COMERCIALIZAR") next
        if (price !~ /^[0-9]+$/ || price + 0 <= 0) next
        print id "\t" price > sellFile
    }
' "$SOURCE"

sort -u -o "$sell" "$sell"
sort -u -o "$skip" "$skip"

nsell=$(wc -l < "$sell" | tr -d ' ')
nskip=$(wc -l < "$skip" | tr -d ' ')

[ "$nsell" -gt 4000 ] || { echo "only $nsell priced rows parsed -- the document's shape changed" >&2; exit 1; }
[ "$nskip" -gt 50 ]   || { echo "only $nskip excluded rows parsed -- the document's shape changed" >&2; exit 1; }

{
cat <<'HEADER'
--[[ The Catalogue -- the price table.

     GENERATED FILE. Do not edit by hand: tools/import_prices.sh rewrites it wholesale
     from tools/reference/PZ_prices_B42.20.4.md. To change one price permanently, add it
     to TC_Overrides.lua, which wins over this table -- and say there why the study is
     wrong, because an override that merely agrees with the table is how the two drift.

     IMPORTED, NOT DERIVED. The study prices every vanilla id one at a time, from 1993 US
     replacement cost and then what the object is worth thirty to ninety days into the
     Knox Event, and it holds relations the old formula had no way to see: a dirty
     variant is 35% of the clean one, a sterilised one 150%, a broken one at most 25%, an
     opened one at most 80%, a pack is worth what its recipe actually yields, and a full
     container never less than the shell it returns.

     These are the integers the shop shows. TC.PRICE_SCALE is 1.0, so nothing is applied
     on top but the sandbox PriceMultiplier.

     Items the study marks as not merchandise are NOT here, and are refused outright by
     TC_ExcludedItems.lua. Leaving them out of this file alone would not do it: the
     formula fallback would price them anyway.
]]

TheCatalogue = TheCatalogue or {}

TheCatalogue.PRICE_TABLE = {
HEADER
awk -F'\t' '{ printf "    [\"%s\"] = %d,\n", $1, $2 }' "$sell"
echo "}"
} > "$PRICES"

{
cat <<'HEADER'
--[[ The Catalogue -- vanilla ids that are not merchandise.

     GENERATED FILE. Do not edit by hand: tools/import_prices.sh rewrites it wholesale
     from tools/reference/PZ_prices_B42.20.4.md, from the rows that study marks EXCLUIR.

     These are not items anyone would call worthless -- a low price is what worthless
     means. They are not OBJECTS: debug and test fixtures, corpses, the wound and bandage
     overlays the health system paints on a body, hair and beard stubble, and the Money
     the catalogue itself pays in.

     WHY THIS FILE EXISTS AT ALL, rather than just leaving them unpriced. Nothing here is
     the last word on price -- the formula fallback is. Omit a price and the fallback
     works one out, and roundPrice floors at $1, so a debug water bucket appears on the
     shelf for a dollar. The index has to refuse them BEFORE any pricing layer is asked,
     which is what TC.EXCLUDED_ITEMS does.

     Merged into the hand-written list in TC_Config.lua rather than replacing it: that
     one holds our own parcels, which are packaging and not vanilla's business.
]]

TheCatalogue = TheCatalogue or {}
TheCatalogue.EXCLUDED_ITEMS = TheCatalogue.EXCLUDED_ITEMS or {}

local NOT_MERCHANDISE = {
HEADER
awk '{ printf "    \"%s\",\n", $0 }' "$skip"
cat <<'FOOTER'
}

for _, id in ipairs(NOT_MERCHANDISE) do
    TheCatalogue.EXCLUDED_ITEMS[id] = true
end
FOOTER
} > "$EXCLUDED"

echo "prices    $nsell tradable ids -> $PRICES"
echo "excluded  $nskip non-merchandise ids -> $EXCLUDED"
